### ISSUE TITLE
Error when running the Queue

### ISSUE THREAD

**Issue by h54917** [Nlar/ComfyUI_CartoonSegmentation#3]
[2024-08-09 05:37:28,474]INFO:got prompt
[2024-08-09 05:37:28,588]ERROR:!!! Exception during processing!!! invalid load key, 'v'.
[2024-08-09 05:37:28,589]ERROR:Traceback (most recent call last):
  File "/root/autodl-tmp/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_CartoonSegmentation/segmentation.py", line 117, in ani_segmentation
    net = AnimeInsSeg(ckpt, mask_thr=mask_thres, refine_kwargs=refine_kwargs)
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_CartoonSegmentation/CartoonSegmentation/animeinsseg/__init__.py", line 197, in __init__
    ckpt = torch.load(ckpt, map_location='cpu')
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Nlar** [comment]
I notice that the torch load is using cpu.  Can you please confirm that pytorch is working using your video card and confirm that you are using version cuda version 11.8

As a side note it looks like you are running your conda environment as root.  This may not be ideal.  

If you have a workflow available I can try it on my system as well.

**Comment by h54917** [comment]
Thank u very much, I had fixed the problem. Now ur Nodes just run perfect! Thanks u very much.I will write the problem I met and How I fixed on github.:D




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nlar/ComfyUI_CartoonSegmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月9日(星期五) 中午1:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nlar/ComfyUI_CartoonSegmentation] Error when running the Queue (Issue #3)





 
I notice that the torch load is using cpu.  Can you please confirm that pytorch is working using your video card and confirm that you are using version cuda version 11.8
 
As a side note it looks like you are running your conda environment as root.  This may not be ideal.
 
If you have a workflow available I can try it on my system as well.

**Comment by h54917** [comment]
It's the problem of the model. I used 'git clone' to clone the models of CartoonSegmentation to my disk, but I forgot to install 'git lfs' so what I cloned is just index to the models other than real models. 
Another hard question is the install of 'cupy', my cpython version is 3.0, which cant build cupy.It take me a lot of time to fix this problem. The solution is use pip to install cypthon2.9.

**Comment by Nlar** [comment]
I am glad you were able to resolve your problem.   Thank you for stating your solution.
